### ISSUE TITLE
Does not appear to work in the latest version of Unity (2020.3.15f2).

### ISSUE THREAD

**Issue by BlueAwesomeDinosaur** [kenamis/UMADismemberment#1]
I recently imported the script from the project and placed it onto the UMA character above the animator, but it does not seem to work. I did provide it a material and messed around with the sliders, but it did not work. Is there a fix for this?

**Comment by kenamis** [comment]
No, sorry. I have not used this or UMA for years now. If you post the errors, I can maybe point you in the right direction.  You could also try asking on the UMA discord.

**Comment by BlueAwesomeDinosaur** [comment]
Unfortunately, it did not give any errors; it just did not do anything. However, when used with the DCA Render, it does give errors.

**Comment by BlueAwesomeDinosaur** [comment]
![image](https://user-images.githubusercontent.com/88523101/128514259-46c48401-3235-4256-a461-47dbbc97869c.png)
Here are the errors I get when I use the script in combination with a DCA Render Manager. The DCA Render Manager is just making parts of the head shadow only so I can see in first person.

**Comment by kenamis** [comment]
closing all issues and deprecating this repo
